repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: "Rust: format code with cargo fmt"
      - id: cargo-check
        name: "Rust: check code with cargo check"
      - id: clippy
        name: "Rust: run clippy lints"

  - repo: local
    hooks:
      - id: cargo-test
        name: Run cargo test
        description: Run cargo test to make sure all tests pass
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
